name: Godot RPG Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Godot 4.3
        uses: chickensoft-games/setup-godot@v2
        with:
          version: "4.3.0"
          use-dotnet: false


      - name: Install Android Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.3.stable

          wget -q https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz

          unzip -o Godot_v4.3-stable_export_templates.tpz \
          -d ~/.local/share/godot/export_templates/4.3.stable

          mv ~/.local/share/godot/export_templates/4.3.stable/templates/* \
          ~/.local/share/godot/export_templates/4.3.stable/

          rm -rf ~/.local/share/godot/export_templates/4.3.stable/templates

          rm Godot_v4.3-stable_export_templates.tpz


      - name: Check Godot Templates
        run: |
          echo "Checking templates..."
          ls -la ~/.local/share/godot/export_templates/4.3.stable


      - name: Install Android SDK
        uses: android-actions/setup-android@v3


      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      - name: Build Android APK
        run: |
          mkdir -p build

          godot \
          --headless \
          --verbose \
          --path . \
          --export-release "Android" \
          build/game.apk


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Godot-RPG-Android-APK
          path: build/game.apk
