name: Godot RPG Android Build

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Repository
        uses: actions/checkout@v4


      - name: Setup Godot 4.3
        uses: chickensoft-games/setup-godot@v2
        with:
          version: "4.3.0"
          use-dotnet: false


      - name: Install Godot Android Export Templates
        run: |
          mkdir -p ~/.local/share/godot/export_templates/4.3.stable

          wget -O templates.tpz \
          https://downloads.tuxfamily.org/godotengine/4.3/Godot_v4.3-stable_export_templates.tpz

          mkdir templates

          unzip -o templates.tpz -d templates

          cp -r templates/templates/* \
          ~/.local/share/godot/export_templates/4.3.stable/

          echo "Checking templates..."
          ls -la ~/.local/share/godot/export_templates/4.3.stable


      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"


      - name: Setup Android SDK
        uses: android-actions/setup-android@v3


      - name: Verify Godot Project
        run: |
          echo "Project files:"
          ls -la
          echo "Export presets:"
          cat export_presets.cfg


      - name: Build Android APK
        run: |
          mkdir -p build

          godot \
          --headless \
          --verbose \
          --path . \
          --export-release "Android" \
          build/game.apk


      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Naruto-RPG-Android-APK
          path: build/game.apk
